"""Models used for illustration."""

import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


class LinearModel:
    """Linear model with noise."""

    def __init__(self, slope=1, intercept=0, noise_variance=0):
        """Initialize the linear model.

        Parameters
        ----------
        slope : float, optional
            Slope of the linear model, by default 1
        intercept : float, optional
            Intercept of the linear model, by default 0
        noise_variance : float, optional
            Variance of the noise, by default 0
        """
        self.slope = slope
        self.intercept = intercept
        self.noise_variance = noise_variance

    def noise(self, num_samples):
        """Generate noise samples.

        The noise samples are drawn from a normal distribution with zero mean
        and variance equal to the noise variance.

        Parameters
        ----------
        num_samples : int
            Number of samples to generate

        Returns
        -------
        np.ndarray
            Noise samples with shape (num_samples,)
        """
        return np.random.normal(0, self.noise_variance, num_samples)

    def f(self, x, slope=None, intercept=None):
        """Linear model function.

        The linear model function is defined as y = slope * x + intercept.

        Parameters
        ----------
        x : np.ndarray
            Input data with shape (num_samples,)
        slope : float, optional
            Slope of the linear model, by default None, so the self.slope is
            used.
        intercept : float, optional
            Intercept of the linear model, by default None, so the
            self.intercept is used.

        Returns
        -------
        np.ndarray
            Output data with shape (num_samples,)
        """
        slope = slope or self.slope
        intercept = intercept or self.intercept
        return slope * x + intercept

    def forward(self, x):
        """Generate forward predictions.

        The forward predictions are generated by the linear model with added
        noise.

        Parameters
        ----------
        x : np.ndarray
            Input data with shape (num_samples,)
        """
        return self.f(x) + self.noise(len(x))

    def fit(self, x, y):
        """Fit the linear model to the data.

        The fit is performed using a linear regression model.

        Parameters
        ----------
        x : np.ndarray
            Input data with shape (num_samples,)
        y : np.ndarray
            Target data with shape (num_samples,)

        Returns
        -------
        float, float
            Fitted slope and intercept
        """
        reg = LinearRegression().fit(x.reshape(-1, 1), y)
        return reg.coef_[0], reg.intercept_

    def loss_surface(
        self,
        x,
        y,
        slopes_range=(-1, 3),
        intercepts_range=(-1, 1),
        grid_size=30,
        loss_function=mean_squared_error,
    ):
        """Compute the loss surface of the linear model.

        The loss surface is computed by evaluating the loss function for all
        combinations of slopes and intercepts.

        Parameters
        ----------
        x : np.ndarray
            Input data with shape (num_samples,)
        y : np.ndarray
            Target data with shape (num_samples,)
        slopes_range : tuple, optional
            Range of slopes to evaluate, by default (-1, 3)
        intercepts_range : tuple, optional
            Range of intercepts to evaluate, by default (-1, 1)
        grid_size : int, optional
            Number of grid points in each dimension, by default 30
        mean_squared_error : callable, optional
            Loss function to evaluate, by default mean_squared_error

        Returns
        -------
        np.ndarray, np.ndarray, np.ndarray
            Loss surface, slopes, intercepts
        """
        # Create grid
        slopes = np.linspace(*slopes_range, grid_size)
        intercepts = np.linspace(*intercepts_range, grid_size)

        # Compute loss surface
        loss = np.zeros((grid_size, grid_size))
        for i, slope in enumerate(slopes):
            for j, intercept in enumerate(intercepts):
                y_hat = self.f(x, slope, intercept)
                loss[i, j] = loss_function(y, y_hat)

        return loss, slopes, intercepts
